<a href="https://colab.research.google.com/github/sam098761212-glitch/Leeseungsoo-AI_CLASS/blob/main/%EA%B8%B0%EA%B3%84%ED%95%99%EC%8A%B5%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D_9_28_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
import seaborn as sns


columns = [
    'buying',
    'maint',
    'doors',
    'persons',
    'lug_boot',
    'safety',
    'class'
]


df = pd.read_csv('car.data', names=columns)


df.head(10)

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc
5  vhigh  vhigh     2       2      med   high  unacc
6  vhigh  vhigh     2       2      big    low  unacc
7  vhigh  vhigh     2       2      big    med  unacc
8  vhigh  vhigh     2       2      big   high  unacc
9  vhigh  vhigh     2       4    small    low  unacc

In [11]:
# 다른방법
dt = pd.read_csv('car.data', names=columns)

dt.columns = ['buying',
    'maint',
    'doors',
    'persons',
    'lug_boot',
    'safety',
    'class']

dt.head(10)

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc
5  vhigh  vhigh     2       2      med   high  unacc
6  vhigh  vhigh     2       2      big    low  unacc
7  vhigh  vhigh     2       2      big    med  unacc
8  vhigh  vhigh     2       2      big   high  unacc
9  vhigh  vhigh     2       4    small    low  unacc

In [22]:
X = df.drop("class",axis = 1)
y = df["class"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.preprocessing import LabelEncoder
label_encoders = {}
for column in columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])

df

      buying  maint  doors  persons  lug_boot  safety  class
0          3      3      0        0         2       1      2
1          3      3      0        0         2       2      2
2          3      3      0        0         2       0      2
3          3      3      0        0         1       1      2
4          3      3      0        0         1       2      2
...      ...    ...    ...      ...       ...     ...    ...
1723       1      1      3        2         1       2      1
1724       1      1      3        2         1       0      3
1725       1      1      3        2         0       1      2
1726       1      1      3        2         0       2      1
1727       1      1      3        2         0       0      3

[1728 rows x 7 columns]

In [41]:
# 의사결정나무

from sklearn.tree import DecisionTreeClassifier
model_D = DecisionTreeClassifier()
model_D.fit(X_train, y_train)

pred_df_D = model_D.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, pred_df_D))

0.9739884393063584

In [42]:
# 랜덤포레스트

from sklearn.ensemble import RandomForestClassifier
model_R = RandomForestClassifier()
model_R.fit(X_train,y_train)

pred_df_R = model_R.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, pred_df_R))

0.976878612716763

In [43]:
# 로지스틱회귀

from sklearn.linear_model import LogisticRegression
model_D = LogisticRegression()
model_D.fit(X_train,y_train)

pred_df_L = model_D.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, pred_df_L))

0.6705202312138728

In [49]:
# 성능비교 와 평가지표

from sklearn.metrics import classification_report, confusion_matrix

# DecisionTree

print(classification_report(y_test, pred_df_D))

cmD = confusion_matrix(y_test,pred_df_D)
print(cmD)

              precision    recall  f1-score   support

           0       0.94      0.95      0.95        87
           1       0.75      0.86      0.80         7
           2       0.99      0.99      0.99       236
           3       1.00      0.88      0.93        16

    accuracy                           0.97       346
   macro avg       0.92      0.92      0.92       346
weighted avg       0.97      0.97      0.97       346

[[ 83   2   2   0]
 [  1   6   0   0]
 [  2   0 234   0]
 [  2   0   0  14]]

In [50]:
# RandomForest

print(classification_report(y_test, pred_df_R))

cmR = confusion_matrix(y_test, pred_df_R)
print(cmR)

              precision    recall  f1-score   support

           0       0.92      0.99      0.96        87
           1       0.86      0.86      0.86         7
           2       1.00      0.99      0.99       236
           3       1.00      0.81      0.90        16

    accuracy                           0.98       346
   macro avg       0.95      0.91      0.93       346
weighted avg       0.98      0.98      0.98       346

[[ 86   1   0   0]
 [  1   6   0   0]
 [  3   0 233   0]
 [  3   0   0  13]]

In [51]:
# LogisticRegression

print(classification_report(y_test, pred_df_L))

cmL = confusion_matrix(y_test, pred_df_L)
print(cmL)

              precision    recall  f1-score   support

           0       0.33      0.10      0.16        87
           1       0.00      0.00      0.00         7
           2       0.71      0.93      0.81       236
           3       0.27      0.19      0.22        16

    accuracy                           0.67       346
   macro avg       0.33      0.31      0.30       346
weighted avg       0.58      0.67      0.60       346

[[  9   0  72   6]
 [  0   0   7   0]
 [ 14   0 220   2]
 [  4   0   9   3]]

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))